# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-29 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legislation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.URLField()),
                ('text', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='legislator',
            name='gender',
            field=models.CharField(choices=[('F', 'Female'), ('N', 'Nonbinary'), ('M', 'Male')], max_length=1),
        ),
    ]
